### ISSUE TITLE
Required terms must have examples and preferably validation constraints

### ISSUE THREAD

**Issue by turbomam** [turbomam/mixs-envo-struct-knowl-extraction#45]
>   generated/mixs_v6.xlsx.examples.yaml::$.exhaustive_test_set[0]: 'api' is a required property
>   generated/mixs_v6.xlsx.examples.yaml::$.exhaustive_test_set[0]: 'basin' is a required property
>   generated/mixs_v6.xlsx.examples.yaml::$.exhaustive_test_set[0]: 'coll_site_geo_feat' is a required property
>   generated/mixs_v6.xlsx.examples.yaml::$.exhaustive_test_set[0]: 'collection_date' is a required property
>   generated/mixs_v6.xlsx.examples.yaml::$.exhaustive_test_set[0]: 'env_broad_scale' is a required property
>   generated/mixs_v6.xlsx.examples.yaml::$.exhaustive_test_set[0]: 'env_local_scale' is a required property
>   generated/mixs_v6.xlsx.examples.yaml::$.exhaustive_test_set[0]: 'env_medium' is a required property
>   generated/mixs_v6.xlsx.examples.yaml::$.exhaustive_test_set[0]: 'iwf' is a required property
>   generated/mixs_v6.xlsx.examples.yaml::$.exhaustive_test_set[0]: 'microbial_biomass_meth' is a required property
>   generated/mixs_v6.xlsx.examples.yaml::$.exhaustive_test_set[0]: 'occup_density_samp' is a required property
>   generated/mixs_v6.xlsx.examples.yaml::$.exhaustive_test_set[0]: 'water_cut' is a required property

**Comment by turbomam** [comment]
optionally import the examples from `data/ExhaustiveTestClassCollection-example-data.yaml` or something more expert-curated

**Comment by turbomam** [comment]
```SQL
select
	value ,
	count(1)
from
	all_attribs aa
where
	harmonized_name = 'coll_site_geo_feat'
group by
	value
having
	count(1) > 1
order by
	count(1) desc ;
```
	
no values:
- `api`
- `basin`
- `iwf`
- `occup_density_samp`
- `water_cut`

**Comment by turbomam** [comment]
```yaml
api:
  name: api
  annotations:
    Preferred_unit:
      tag: Preferred_unit
      value: degrees API
  description: 'API gravity is a measure of how heavy or light a petroleum liquid
    is compared to water (source: https://en.wikipedia.org/wiki/API_gravity) (e.g.
    31.1   API)'
  title: API gravity
  slot_uri: MIXS:0000157
  multivalued: false
  range: string
  required: true
  pattern: ^[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)? \S.*\S$
```

**Comment by turbomam** [comment]
```yaml
basin:
  name: basin
  description: Name of the basin (e.g. Campos)
  title: basin name
  slot_uri: MIXS:0000290
  multivalued: false
  range: string
  required: true
```

**Comment by turbomam** [comment]
```yaml
water_cut:
  name: water_cut
  annotations:
    Preferred_unit:
      tag: Preferred_unit
      value: percent
  description: Current amount of water (%) in a produced fluid stream; or the average
    of the combined streams
  title: water cut
  slot_uri: MIXS:0000454
  multivalued: false
  range: string
  required: true
  pattern: ^[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)? \S.*\S$
```
